# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0235a3c1a7acb7fa7682a8a155099b5256a918392062d53cad3781b0f931ebedc4f2bb9fc7902312307799d33800a793d7a33c53ade16de97a0fc9b94f05c30b

test:
  secret_key_base: 7013c1488d278c18d47c1a903ae3fc43499e662cd373166b6e86b1170d3760ea1a4f1a378598ff8ad66298ebe2de9a764955f1b0858cfa1421b57cccd402d9f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
